// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmuc8uJ7eeZU_MWfSI-CuTGoNY7xtVD4',
    appId: '1:145467382685:web:75ee244edecac64cedad74',
    messagingSenderId: '145467382685',
    projectId: 'servio-edd31',
    authDomain: 'servio-edd31.firebaseapp.com',
    storageBucket: 'servio-edd31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB6O0Xckcp3mlcEzlLaLmtl4iFE7DFiSc',
    appId: '1:145467382685:android:ed62455d590fdefeedad74',
    messagingSenderId: '145467382685',
    projectId: 'servio-edd31',
    storageBucket: 'servio-edd31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeLw8EjdTjXiqTIVkP-XN07_QGWg-EQw',
    appId: '1:145467382685:ios:aa20aa1a0f9a8659edad74',
    messagingSenderId: '145467382685',
    projectId: 'servio-edd31',
    storageBucket: 'servio-edd31.firebasestorage.app',
    iosBundleId: 'com.example.servio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeLw8EjdTjXiqTIVkP-XN07_QGWg-EQw',
    appId: '1:145467382685:ios:aa20aa1a0f9a8659edad74',
    messagingSenderId: '145467382685',
    projectId: 'servio-edd31',
    storageBucket: 'servio-edd31.firebasestorage.app',
    iosBundleId: 'com.example.servio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPmuc8uJ7eeZU_MWfSI-CuTGoNY7xtVD4',
    appId: '1:145467382685:web:5919ad6b42fe25bbedad74',
    messagingSenderId: '145467382685',
    projectId: 'servio-edd31',
    authDomain: 'servio-edd31.firebaseapp.com',
    storageBucket: 'servio-edd31.firebasestorage.app',
  );
}
